spring.application.name=demo

# Azure SQL Database Connection Properties
spring.datasource.url=jdbc:sqlserver://alphaeci.database.windows.net:1433;database=parches_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=Vanessa@alphaeci
spring.datasource.password=Flash2022
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect