spring.application.name=demo

# PostgreSQL Connection Properties
spring.datasource.url=jdbc:postgresql://alphaeci.database.windows.net:5432/tu_nombre_de_base_de_datos?sslmode=require
spring.datasource.username=Vanessa
spring.datasource.password=Flash2022
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
